services:
  mongodb:
    image: mongo:latest
    container_name: i16e-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: N0virus1!
      MONGO_INITDB_DATABASE: i16e-db
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - i16e-dev-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  n8n:
    image: n8nio/n8n:latest
    container_name: i16e-n8n-dev
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=mongodb
      - DB_MONGODB_CONNECTION_URL=mongodb://admin:N0virus1!@mongodb:27017/n8n?authSource=admin
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
    volumes:
      - n8n_dev_data:/home/node/.n8n
    networks:
      - i16e-dev-network
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mongodb-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: i16e-api-dev
    container_name: i16e-api-dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://admin:N0virus1!@mongodb:27017/i16e-db?authSource=admin
      - PORT=3001
      - NODE_ENV=development
    networks:
      - i16e-dev-network
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_dev_data:
    driver: local
  n8n_dev_data:
    driver: local

networks:
  i16e-dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16